#include <iostream>
#include <cmath>

using namespace std;

int main()
{
    int HORAINICIAL,MINUTOINICIAL,HORAFINAL,MINUTOFINAL;
    double HORAS,MINUTOS;
    double TOTALHORAS,TOTALMINUTOS;

    cin >> HORAINICIAL >> MINUTOINICIAL >> HORAFINAL >> MINUTOFINAL;

    HORAS = HORAFINAL - HORAINICIAL;
    MINUTOS = MINUTOFINAL - MINUTOINICIAL;

    if(HORAFINAL > HORAINICIAL and MINUTOFINAL > MINUTOINICIAL){
        TOTALHORAS = HORAFINAL - HORAINICIAL;
        TOTALMINUTOS = MINUTOFINAL - MINUTOINICIAL;
    }
    else if(HORAFINAL == HORAINICIAL and MINUTOFINAL == MINUTOINICIAL){
        TOTALHORAS = 24;
        TOTALMINUTOS = 0;
    }
    else if(HORAFINAL >= HORAINICIAL and MINUTOFINAL < MINUTOINICIAL){
        TOTALHORAS = 0;
        TOTALMINUTOS = 60 - abs(MINUTOFINAL - MINUTOINICIAL);
    }
    else if(HORAFINAL < HORAINICIAL and MINUTOFINAL < MINUTOINICIAL){
        TOTALHORAS = 24 - 1 - (abs(HORAS));
        TOTALMINUTOS = 60 - abs(MINUTOS);
    }
    else if(HORAFINAL < HORAINICIAL and MINUTOFINAL > MINUTOINICIAL){
        TOTALHORAS = 24 - (abs(HORAS));
        TOTALMINUTOS = abs(HORAS);
    }

    cout << "O JOGO DUROU " << TOTALHORAS << " HORA(S) E " << TOTALMINUTOS << " MINUTO(S)\n";

    return 0;
}